### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by groud**
I replaced the node editor window Icon by a colorless one.
I believe it stands out a little bit less and blends better in the editor.

How do you think ? :)

### CODE REVIEW

**Comment by pmhpereira** [comment]
Can you provide a screenshot with the new icons? I made the current ones and need you to convince me yours are better. :P

**Comment by groud** [comment]
Here it is : 
screenshot

**Comment by Seneral** [comment]
Does match the style of the default icons better imo. Doesn't matter too much though but I'd merge it if everyone is ok;)

**Comment by pmhpereira** [comment]
When I added the current ones (with color), I made them with the objective of looking different from the default Unity ones, to reinforce the fact that it is a plugin and that it support various types of nodes.

Your version is simpler but blends better with the UI. Looks cool!

For reference, the current ones:


Let's see what @Seneral thinks. :-)

**Comment by pmhpereira** [comment]
I'm not against it. I'll forever keep mine in my heart. :heart:
Merge away! :D

**Comment by groud** [comment]
@pmhpereira I do not have unity pro, but here is a montage ^^
donthaveunitypro

**Comment by pmhpereira** [comment]
@groud I don't either! ;-)

Looks good to me!

**Comment by Seneral** [comment]
I'm currently kinda rushing to get a commit to the action node out before sleeping, we can see tomorrow, ok?

**Pull request merged**
