### PR TITLE
First step before replacing documentation by a markdown version.

### PR DESCRIPTION
**Pull request by groud**
These are the first sources for the documentation.
Writen with Markdown and compiled with [Mkdocs](http://www.mkdocs.org/).

A preview :
node editor 2016-03-15 23-08-43

### CODE REVIEW

**Comment by Seneral** [comment]
Hey @groud, will you update this with the other pages? It looks amazing btw:)

**Comment by groud** [comment]
Well, I can do that.
But is it really useful if we plan to put the whole documentation into the wiki repository ?
I am still waiting for a decision from @Baste-RainGames about giving us right on this wiki repository (I have no idea about how to do that, btw :/ )

**Comment by Seneral** [comment]
We can do both since we can use MK for both, right?
Additionally a standalone online documentation makes a good impression I think;)
Also I could create the wiki pages, but only @Baste-RainGames can elect contributors, so if you could respond that'd be great;)
I'm currently trying to install mkDocs

**Comment by groud** [comment]
If we can the put all MD files into the wiki repository with the compilation files (the mkdocs.yml file), I though we would keep only the compiled (i.e. html) files into the gh-pages branch and into the docs folder.

**Comment by Seneral** [comment]
Yup, sounds about right.
On a side note, I seem unable to install mkDocs :(
When the installation notes refer to a command (MKDocs, pip, ...) which console do I use? The normal cmd reports 'python' does not exist even when having it installed and the python console doesn't accept these commands either. I'm not that into python to get this :D

**Comment by groud** [comment]
Normally it should work if you use cmd, but you can use powershell instead.
If it does not work with 'python', try 'python.exe' instead.

Check your python version, the 3.5 one comes with pip, while the 2.* don't.

Pip commands should also be executed into cmd/powershell shells, not into the python's one.

**Comment by Seneral** [comment]
Yeah it does work now, just missed to add python to the path variable when installing. Only realized this as I tried the older 2.7.11 which actually explained what that does, I simply unchecked it in the first install because I though I didn't need it :'D
It is looking really pretty. Though the theme your using is deprecated, it says...
If you don't mind I'll experiment with it a bit:)

**Comment by groud** [comment]
Well, do not hesitate to checkout my branch, create a new branch from there, push your changes into your own fork, then create a pull request into my branch. ^^

**Comment by groud** [comment]
I merged the pull request but did not close it, you should be able to add other modifications into the pull request (Well I think ^^)

**Comment by Seneral** [comment]
Yep good idea:)
The changes are not yet committed so we should leave this open until we're happy with the page so far (of course it's a ongoing WIP)
For me that means only the style to go;)
Do you have any ideas/improvements?

**Comment by Seneral** [comment]
Maybe we can structure it a bit better, including subpages, etc.
Not today though, atleast for me:)

**Comment by Seneral** [comment]
Also, any idea how we can remove the duplicate page link 'Node Editor Framework' and 'Home' to the index page?

**Comment by groud** [comment]
I merged the pull request. 
The check failed comes from travisCl, I was testing this module that can perform building tests when a pull request is made. :)

Actually I did not check the content yet, I do not know the Framework enough to have pertinent comments on the documentation ^^

**Comment by groud** [comment]
Double link removed. :)

**Comment by Seneral** [comment]
Oh misunderstood your previous post

Also, that was the reason I asked, this won't compile;)

**Comment by groud** [comment]
@Seneral , lol, this worked fine with another project.
I'll fix this

**Comment by Seneral** [comment]
Sorry it will compile but the index.md page is completely left out.

**Comment by groud** [comment]
Well, I more or less fixed this... ^^

**Comment by Seneral** [comment]
Really good idea! That'll do:)

**Comment by Seneral** [comment]
Wait: this also hides the search field :O
It is also the first element in a list:(

**Comment by Seneral** [comment]
Can you exclude classes from css? Then excluding  'navbar-right' should do it

**Comment by Seneral** [comment]
cThis css works:
```
ul.nav.navbar-nav:not(.navbar-right) li:first-child {
	display: none;
}
```

**Comment by groud** [comment]
Done.

**Comment by Seneral** [comment]
Cool

**Pull request merged**
