### PR TITLE
Added .gitignore

### PR DESCRIPTION
**Pull request by pmhpereira**
Added filters for the `meta` files immediately created by Unity when the project is imported.

### CODE REVIEW

**Comment by Seneral** [comment]
Those are needed, especially for the scriptable object types, in order for the save files not to break.

**Comment by pmhpereira** [comment]
The files will still be created by Unity and won't change if the project is updated...

The reasoning for this `.gitignore` is that once you test/modify the project with Unity, it will create all this extra *.meta files that will appear on Git to be committed. If you want to make a Pull Request, you have to ignore / delete these files by hand, every single time.

**Comment by Seneral** [comment]
Ok, didn't know the existing ones are kept;)
No problem then!

**Comment by pmhpereira** [comment]
I figured it was a problem of communication. :-)

**Comment by Seneral** [comment]
Well no problem anyway it will make committing way easier:)

**Pull request merged**
