### PR TITLE
Canvas clipping for Bezier and Lines

### LINKED ISSUE #44: Clipping for custom runtime Bezier drawing
**Description:** As handles cannot be used at runtime, I created a bezier drawing function some time ago. It works but currently does not provide clipping (not only for optimisation, but it will extend over bounds).

**State:** None. To get the bounds to clip to, use GUIScalingUtility.cs, there are properties to get the parent group rect.

**Location:** RTEditorGUI.cs

### PR DESCRIPTION
**Pull request by pmhpereira**
Fixes #44.

There is a minor issue with clipping __some__ Beziers curves when they are really long, where some segments disappear instead of being clipped. It's only really noticeable with max zoom.

I think this might be related with the orientation of a line (order of the vertices), but I couldn't pinpoint exactly why or how to solve it.

### CODE REVIEW

**Comment by Seneral** [comment]
^^ Line comment :)

Thanks very much! Just one quetion: Why did you remove the optimizations for line thickness of 1? They were not used by the Node Editor but it is a 'Uttility' ;)
Similar with the bounds, I would very much see it using GUIScaluUitility.getTopRect which then works universally:) The performance shouldn't be influenced at all, even though it's a reflection call technically, but by making use of a delegate the overhead is negliable...

**Comment by pmhpereira** [comment]
I actually profiled the old implementation vs. the new one, and the special cases for width = 1 weren't particularly faster.

**Comment by Seneral** [comment]
Well I won't complain then:) What about the getTopRect call? Did you test that?

**Comment by pmhpereira** [comment]
I also tried using __GUIScaluUitility.getTopRect__ but was getting an exception about "pushing more than pulling" or something like that and I didn't know how to solve it.

But that was when I tried to clip inside "DrawLineSegment()" which is called a bunch of times for Beziers. I'll try with the current implementation. :D

**Comment by pmhpereira** [comment]
I also removed __UnityEditor.Handles.DrawBezier()__ when the editor is not running because it wasn't particularly faster too: 0.01ms vs 0.02ms for ~20 Béziers.

**Comment by Seneral** [comment]
I tried with about 1000 beziers more than once and it was immensely faster (don't know values, about 3x), and that was when the clipping wasn't even implemented:O May be that your changes did make it alot faster (especially in getBezierPoint)

**Comment by pmhpereira** [comment]
__GUIScaluUitility.getTopRect__ doesn't work as expected. The retrieved rect has the same width/height, but the wrong positions.

**Comment by Seneral** [comment]
Hm, then maybe try the screenspace version?

**Comment by pmhpereira** [comment]
The new GetBezierPoint() is only 30% faster. And I agree that for 1000 béziers the native should be a lot faster. But I stil haven't seen anyone using a canvas with 1000 connections. :P

**Comment by pmhpereira** [comment]
Same result. I'm testing with RuntimeNodeEditor with a smaller rect centered in the viewport, so I can drag the canvas on all four sides.

**Comment by pmhpereira** [comment]
The expected rect is on the left; the one returned from GUIScaluUitility.getTopRect is on the right.

**Comment by Seneral** [comment]
If I'm not mistaken getTopRect should return the rect as it was specified in the group creation and getTopRectScreenSpace should return the same rect in screen space.... Atleast that's what I remember. Seems like they getTopeRect returns what getTopRectScreenSpace  should return now though:( Can you try swapping them? Can you give me the output of both functions to compare?

**Comment by Seneral** [comment]
But wait, this IS expected behaviour! Due to the zooming, the rect actually IS transformed into screen space *facepalm*
So you should be able work with this without problems:)

**Comment by pmhpereira** [comment]
getTopRect and getTopRectScreenSpace always return the same rect (even for different zooms).

It doesn't work as intended because even though they have the expected width/height, their x,y is different.

**Comment by Seneral** [comment]
as I said above at the time of calling the zooming system has transformed the rect into screen space for the zooming to not be clipped (this is what makes the system so special:) ). So it makes sense they return the same value;)

**Comment by pmhpereira** [comment]
So what is the solution? Keep it as it is?

**Comment by Seneral** [comment]
It should work if you clip with those, doesn't it? Because the bezier points should be in the apropriate space already, too...

**Comment by pmhpereira** [comment]
But it doesn't work, because the clipping rect position is wrong. :D
It's better if you try it and see what I mean.

**Comment by Seneral** [comment]
Well I downloaded the last commit which has the manual clip rect creation fro mthe node editor canvas enabled. This works for you, you say?
I get a clip offset of 100/100 when specifying the same for the canvas rect position. That means the getTopRect version should work for me, right?

**Comment by pmhpereira** [comment]
But does it clip fine for you?

My "manual clip rect" has the values x: 0; y: 0; width: 600; height: 600.
getTopRect has the values x: 100; y: 100; width: 600; height: 600.

This is weird... Did you specify the same values for "Runtime Node Editor" as I did?

**Comment by Seneral** [comment]
Wait a minute, there are even more oddities. No it does not work fine with getTopRect, but it doesn't either with yours...
Give me a sec to collect some results

**Comment by Seneral** [comment]
Results:
0-100_gettoprect
0-100_manual
100-0_gettoprect
100-0_manual
These show that the getTopRect always uses screenSpace which yields wrong results. The manual technique is working when only the tope rect has to be accounted for. Inconsistent, and hard to adapt to account for all top groups (we would be back to reflection then).
My sugestion is that I'll take a look how I can find a method to transform that back to local space based on the current scale. It is possible:)

**Comment by Seneral** [comment]
Ok a pretty simple solution is to just set the position to Vector2.zero for the getTopRect rect. This does work in all cases and is, if you think about it, pretty logic. You're in you're groups local space, so the group has to be at 0/0. The returned rect is in the second top group space though;) So that does work:)

**Comment by Seneral** [comment]
I also think you made some minor mistakes in the clipping algorithm...
For example the clipping should modify the points so they are exaclty clipped to the edge, right?

**Comment by pmhpereira** [comment]
I just noticed that. It happens for Béziers only, not for straight lines.

As I said in the first post:
"I think this might be related with the orientation of a line (order of the vertices), but I couldn't pinpoint exactly why or how to solve it." :-/

**Comment by Seneral** [comment]
cliperror

^^ Ok didn't remember that
I'll take a look:)

**Comment by Seneral** [comment]
There's also an artifact seen above where both clipped points are connected. Maybe it's related with that somehow.

**Comment by pmhpereira** [comment]
I don't think that behavior is intended though. It's supposed to not show the line between the green arrows.

**Comment by Seneral** [comment]
Indeed, that was what I was complaining about (I think);) I just fixed that though.

**Comment by pmhpereira** [comment]
Awesome! Everything is working now? :D

**Comment by Seneral** [comment]
Nope. Just the connection between clipped points. Anyidea why the code formatting doesn't work?

**Comment by pmhpereira** [comment]
It needs to be ``` and then the code starts in the next line.

```C#
Vector2 curPoint = startPos;
Vector2 nextPoint = curPoint;
bool isClipped = false; // State

for (int segCnt = 1; segCnt <= segmentCount; segCnt++) 
{
	nextPoint = GetBezierPoint ((float)segCnt/segmentCount, startPos, endPos, startTan, endTan);

	if (SegmentRectIntersection(clippingRect, ref curPoint, ref nextPoint)) 
	{
		if (isClipped) 
		{
			GL.Begin (GL.TRIANGLE_STRIP);
			isClipped = false;
		}

		DrawLineSegment (curPoint, new Vector2 (nextPoint.y-curPoint.y, curPoint.x-nextPoint.x).normalized * width/2);
	}	
	else if (!isClipped) 
	{
		isClipped = true;
		GL.End ();
	}
	curPoint = nextPoint;
}

**Comment by Seneral** [comment]
Ok was just confused because I used the insert code button above and it did not work:/

**Comment by pmhpereira** [comment]
Random, but might work, idea: 
We could use GL.Viewport() to specify the viewport where the lines are being drawn, it will be automatically clipped, and we don't need to implement any algorithm.

**Comment by Seneral** [comment]
Seriously? Didn't know THAT :D Definitely worth a try!

**Comment by pmhpereira** [comment]
The problem is that changing the viewport rescales everything inside it, so we need to update the coordinates of every line vertex to make it work.

**Comment by Seneral** [comment]
Just noticed. Cannot get it to work too well...

**Comment by Seneral** [comment]
This is what I've got. Somehow correct scale atleast:
``` C#
GL.PushMatrix ();
GL.Viewport (clippingRect);
GL.LoadIdentity ();
GL.MultMatrix (Matrix4x4.Scale (new Vector3 (1/GUIScaleUtility.getCurrentScale.x, 1/GUIScaleUtility.getCurrentScale.y, 0)));
...
GL.PopMatrix ();
GL.Viewport (new Rect (0, 0, Screen.width, Screen.height));
```

**Comment by Seneral** [comment]
So this means that behind the scenes it does NOT draw directly when calling GL.End? I had the impressio so far...

**Comment by pmhpereira** [comment]
GLEnd() is the counter-part for GLBegin(). It just helps define the scope of which type of primitive is being used.

Behind the scenes, it just pushes the vertices to an array. At the end of the frame, these vertices from all the GLBegin()/GLEnd() are sent to the GPU and are drawn at the same time.

That's what I remember learning from school. I hope I'm not saying it wrong. :D

**Comment by Seneral** [comment]
So we cannot use viewport clipping... on one side I'm delighted we do not have to try get this to work somehow through trial and error, on the other hand it would be a bit cleaner...
Anyway, I'm confident we can sort the last glitch out, soon. But for today I'll focus on the Action Node and UnityFunc again.

**Comment by pmhpereira** [comment]
I'll try to solve this. Worst case scenario, I'll have to use a different clipping algorithm. :D

**Comment by Seneral** [comment]
Hope not, wish you luck:)

**Comment by pmhpereira** [comment]
It's done! :D

The solution was pretty easy, once I figured it out.
When the `nextPoint` is clipped, it needs to be restored to the original position, in order for the clipping of the next step to not display artifacts.

**Comment by Seneral** [comment]
:o
What if I say I had tried the same concept already?
Well, it obviosly missed some important parts lol *facepalm*
Anyway, honestly great job, on the whole clipping feature! Will test this out later:)

**Comment by Seneral** [comment]
The issue seems to still persist for me:
clippingsegementartifacts

**Comment by Seneral** [comment]
A closeup / detailed view to show off the artifacts:
clippingsegementartifactscloseup
I'll use this low res testing environment to debug this behaviour, I'm confident to get some results;)
Anyway, they aren't too critical I suppose...

**Comment by pmhpereira** [comment]
The issue the last commit solved was this:



I actually tested with a lower value of `segmentCount` and I'm aware this happens. I think this might be related to how the DrawLineSegment() works, instead of the clipping. I'll see if I can do something about it.

**Comment by Seneral** [comment]
Ah ok so I thought it was the other fix because the code I posted above already fixed this...
I only chosed the lower segment count so I can debug using Debug.Log;) The error is not that visible with a segment count of 50 but still there.

**Comment by pmhpereira** [comment]
I tested your previous code but I didn't see any changes... Maybe I did something wrong. :-/

**Comment by Seneral** [comment]
Huh? With this code:
``` C#
// Caluclate and draw segments:
Vector2 curPoint = startPos;
Vector2 nextPoint = curPoint;
bool isClipped = false; // State

for (int segCnt = 1; segCnt <= segmentCount; segCnt++) 
{
	nextPoint = GetBezierPoint ((float)segCnt/segmentCount, startPos, endPos, startTan, endTan);
	if (SegmentRectIntersection(clippingRect, ref curPoint, ref nextPoint)) 
	{
		if (isClipped) 
		{
			GL.Begin (GL.TRIANGLE_STRIP);
			isClipped = false;
			//Debug.Log ("Entered Clipping Rect");
		}
		DrawLineSegment (curPoint, new Vector2 (nextPoint.y-curPoint.y, curPoint.x-nextPoint.x).normalized * width/2);
	}
	else if (!isClipped) 
	{
		//Debug.Log ("Exited Clipping Rect");
		isClipped = true;
		GL.End ();
	}
	curPoint = nextPoint;
}
```
The artifact in this image:

should be gone, right? Anyway, it's an artifact less. Some more to go;)

**Comment by pmhpereira** [comment]
I think this is it. \**crosses fingers*\*

**Comment by Seneral** [comment]
Cool, excited to test it out later on the PC:)

**Comment by Seneral** [comment]
Wow, this is a nasty hack;) I'll take a look and try to understand it:)

**Comment by pmhpereira** [comment]
I wasn't able to make it nicer... Sorry! :D

I tested all the possible code alternatives and that one was the only one that works. I agree it isn't pretty to look at...

The double `DrawLineSegment()` call is because TRIANGLE_STRIPS needs 3 vertices to draw something and a single call of `DrawLineSegment()` only adds 2 vertices.

**Comment by Seneral** [comment]
I think I might have found a better solution. Not ready yet;) I've simply debugged and generalized it until it's pretty easy do find out why.

**Comment by Seneral** [comment]
Finally! I got it to work fully, without any artifact:D
I restructured alot, seperated the bezire calculation and made a generic polygonLine drawing function. Isn't worth or anything, just has helped alot with simplifying stuff. And that was a key to success, is seems:)
There's a bit of changed code though, so I decided to just send you the whole Low-Level Drawing region.
``` C#
private static Material lineMaterial;
private static Texture2D lineTexture;

private static void SetupLineMat (Texture tex, Color col) 
{
	if (lineMaterial == null)
		lineMaterial = new Material (Shader.Find ("Hidden/LineShader"));
	if (tex == null)
		tex = lineTexture != null? lineTexture : lineTexture = NodeEditorFramework.Utilities.ResourceManager.LoadTexture ("Textures/AALine.png");
	lineMaterial.SetTexture ("_LineTexture", tex);
	lineMaterial.SetColor ("_LineColor", col);
	lineMaterial.SetPass (0);
}

/// <summary>
/// Draws a Bezier curve just as UnityEditor.Handles.DrawBezier, non-clipped. If width is 1, tex is ignored; Else if tex is null, a anti-aliased texture tinted with col will be used; else, col is ignored and tex is used.
/// </summary>
public static void DrawBezier (Vector2 startPos, Vector2 endPos, Vector2 startTan, Vector2 endTan, Color col, Texture2D tex, float width = 1)
{
	if (Event.current.type != EventType.Repaint)
		return;

	// Calculate optimal segment count
	int segmentCount = CalculateBezierSegmentCount (startPos, endPos, startTan, endTan);
	// Draw bezier with calculated segment count
	DrawBezier (startPos, endPos, startTan, endTan, col, tex, segmentCount, width);
}

/// <summary>
/// Draws a clipped Bezier curve just as UnityEditor.Handles.DrawBezier.
/// If width is 1, tex is ignored; Else if tex is null, a anti-aliased texture tinted with col will be used; else, col is ignored and tex is used.
/// </summary>
public static void DrawBezier (Vector2 startPos, Vector2 endPos, Vector2 startTan, Vector2 endTan, Color col, Texture2D tex, int segmentCount, float width)
{
	if (Event.current.type != EventType.Repaint && Event.current.type != EventType.KeyDown)
		return;

	// Own Bezier Formula
	// Slower than handles because of the horrendous amount of calls into the native api

	Vector2[] bezierPoints = new Vector2[segmentCount+1];

	for (int pointCnt = 0; pointCnt <= segmentCount; pointCnt++) 
	{
		bezierPoints[pointCnt] = GetBezierPoint ((float)pointCnt/segmentCount, startPos, endPos, startTan, endTan);
	}

	DrawPolygonLine (bezierPoints, col, tex, width);
}

/// <summary>
/// Draws a clipped polygon line from the given points. 
/// If width is 1, tex is ignored; Else if tex is null, a anti-aliased texture tinted with col will be used; else, col is ignored and tex is used.
/// </summary>
public static void DrawPolygonLine (Vector2[] points, Color col, Texture2D tex, float width = 1)
{
	if (Event.current.type != EventType.Repaint && Event.current.type != EventType.KeyDown)
		return;

	// Simplify basic cases
	if (points.Length == 1)
		return;
	else if (points.Length == 2)
		DrawLine (points[0], points[1], col, tex, width);

	// Setup for drawing
	SetupLineMat (tex, col);
	GL.Begin (GL.TRIANGLE_STRIP);
	GL.Color (Color.white);

	// Fetch clipping rect
	Rect clippingRect = GUIScaleUtility.getTopRect;
	clippingRect.x = clippingRect.y = 0;

	Vector2 curPoint = points[0], nextPoint, perpendicular;
	bool clippedP0, clippedP1;
	for (int pointCnt = 1; pointCnt < points.Length; pointCnt++) 
	{
		nextPoint = points[pointCnt];

		// Clipping test
		Vector2 curPointOriginal = curPoint, nextPointOriginal = nextPoint;
		if (SegmentRectIntersection (clippingRect, ref curPoint, ref nextPoint, out clippedP0, out clippedP1))
		{ // (partially) visible
			// Calculate apropriate perpendicular
			if (pointCnt < points.Length-1) // Interpolate perpendicular inbetween the point chain
				perpendicular = CalculatePointPerpendicular (curPointOriginal, nextPointOriginal, points[pointCnt+1]);
			else // At the end, there's no further point to interpolate the perpendicular from
				perpendicular = CalculateLinePerpendicular (curPointOriginal, nextPointOriginal);

			if (clippedP0)
			{ // Just became visible, so enable GL again and draw the clipped line start point
				GL.Begin (GL.TRIANGLE_STRIP);
				DrawLineSegment (curPoint, perpendicular * width/2);
			}

			// Draw first point before starting with the point chain. Placed here instead of before because of clipping
			if (pointCnt == 1)
				DrawLineSegment (curPoint, CalculateLinePerpendicular (curPoint, nextPoint) * width/2);
			// Draw the actual point
			DrawLineSegment (nextPoint, perpendicular * width/2);
		}
		else if (clippedP1) // Just became invisible, so disable GL
			GL.End ();

		// Update state variable
		curPoint = nextPointOriginal;
	}
	// Finalize drawing
	GL.End ();
}

/// <summary>
/// Calculates the optimal bezier segment count for the given bezier
/// </summary>
private static int CalculateBezierSegmentCount (Vector2 startPos, Vector2 endPos, Vector2 startTan, Vector2 endTan) 
{
	float straightFactor = Vector2.Angle (startTan-startPos, endPos-startPos) * Vector2.Angle (endTan-endPos, startPos-endPos) * (endTan.magnitude+startTan.magnitude);
	straightFactor = 2 + Mathf.Pow (straightFactor / 400, 1.0f/8);
	float distanceFactor = 1 + (startPos-endPos).magnitude;
	distanceFactor = Mathf.Pow (distanceFactor, 1.0f/4);
	return 4 + (int)(straightFactor * distanceFactor);
}

/// <summary>
/// Calculates the normalized perpendicular vector of the give line
/// </summary>
private static Vector2 CalculateLinePerpendicular (Vector2 startPos, Vector2 endPos) 
{
	return new Vector2 (endPos.y-startPos.y, startPos.x-endPos.x).normalized;
}

/// <summary>
/// Calculates the normalized perpendicular vector for the pointPos interpolated with its two neighbours prevPos and nextPos
/// </summary>
private static Vector2 CalculatePointPerpendicular (Vector2 prevPos, Vector2 pointPos, Vector2 nextPos) 
{
	return CalculateLinePerpendicular (pointPos, pointPos + (nextPos-prevPos));
}

/// <summary>
/// Gets the point of the bezier at t
/// </summary>
private static Vector2 GetBezierPoint (float t, Vector2 startPos, Vector2 endPos, Vector2 startTan, Vector2 endTan) 
{
	float rt = 1 - t;
	float rtt = rt * t;

	return startPos  * rt*rt*rt + 
			startTan * 3 * rt * rtt + 
			endTan   * 3 * rtt * t + 
			endPos   * t*t*t;
}

/// <summary>
/// Adds a line sgement to the GL buffer. Useed in a row to create a line
/// </summary>
private static void DrawLineSegment (Vector2 point, Vector2 perpendicular) 
{
	GL.TexCoord2 (0, 0);
	GL.Vertex (point - perpendicular);
	GL.TexCoord2 (0, 1);
	GL.Vertex (point + perpendicular);
}

/// <summary>
/// Draws a non-clipped line. If tex is null, a anti-aliased texture tinted with col will be used; else, col is ignored and tex is used.
/// </summary>
public static void DrawLine (Vector2 startPos, Vector2 endPos, Color col, Texture2D tex, float width = 1)
{
	if (Event.current.type != EventType.Repaint)
		return;

	// Setup
	SetupLineMat (tex, col);
	GL.Begin (GL.TRIANGLE_STRIP);
	GL.Color (Color.white);
	// Fetch clipping rect
	Rect clippingRect = GUIScaleUtility.getTopRect;
	clippingRect.x = clippingRect.y = 0;
	// Clip to rect
	if (SegmentRectIntersection (clippingRect, ref startPos, ref endPos))
	{ // Draw with clipped line if it is visible
		Vector2 perpWidthOffset = CalculateLinePerpendicular (startPos, endPos) * width / 2;
		DrawLineSegment (startPos, perpWidthOffset);
		DrawLineSegment (endPos, perpWidthOffset);
	}
	// Finalize drawing
	GL.End ();
}

/// <summary>
/// Clips the line between the points p1 and p2 to the bounds rect.
/// Uses Liang-Barsky Line Clipping Algorithm.
/// </summary>
private static bool SegmentRectIntersection(Rect bounds, ref Vector2 p0, ref Vector2 p1)
{
	bool cP0, cP1;
	return SegmentRectIntersection (bounds, ref p0, ref p1, out cP0, out cP1);
}


/// <summary>
/// Clips the line between the points p1 and p2 to the bounds rect.
/// Uses Liang-Barsky Line Clipping Algorithm.
/// </summary>
private static bool SegmentRectIntersection (Rect bounds, ref Vector2 p0, ref Vector2 p1, out bool clippedP0, out bool clippedP1)
{
	float t0 = 0.0f;
	float t1 = 1.0f;
	float dx = p1.x - p0.x;
	float dy = p1.y - p0.y;

	if (ClipTest (-dx, p0.x - bounds.xMin, ref t0, ref t1)) // Left
	{
		if (ClipTest (dx, bounds.xMax - p0.x, ref t0, ref t1)) // Right
		{
			if (ClipTest (-dy, p0.y - bounds.yMin, ref t0, ref t1)) // Bottom
			{
				if (ClipTest (dy, bounds.yMax - p0.y, ref t0, ref t1)) // Top
				{
					clippedP0 = t0 > 0;
					clippedP1 = t1 < 1;

					if (clippedP1)
					{
						p1.x = p0.x + t1 * dx;
						p1.y = p0.y + t1 * dy;
					}

					if (clippedP0)
					{
						p0.x = p0.x + t0 * dx;
						p0.y = p0.y + t0 * dy;
					}

					return true;
				}
			}
		}
	}

	clippedP1 = clippedP0 = true;
	return false;
}

/// <summary>
/// Liang-Barsky Line Clipping Test
/// </summary>
private static bool ClipTest(float p, float q, ref float t0, ref float t1)
{
	float u = q / p;

	if (p < 0.0f)
	{
		if (u > t1)
			return false;
		if (u > t0)
			t0 = u;
	}
	else if (p > 0.0f)
	{
		if (u < t0)
			return false;
		if (u < t1)
			t1 = u;
	}
	else if (q < 0.0f)
		return false;

	return true;
}
```

**Comment by pmhpereira** [comment]
I tested and found a minor bug with spiky lines. I solved that already.

It looks good to merge now. Finally. :D

**Comment by Seneral** [comment]
Cool! Didn't know about these spiky lines but good that you resolved that! :)
Huge amount of work but it was worth it;)

**Pull request merged**
