### PR TITLE
Replace DrawTexture by DrawTexWithTexCoords

### PR DESCRIPTION
**Pull request by groud**
A more efficient way to tile a texture.

### CODE REVIEW

**Comment by groud** [comment]
Do not merge yet, I would consequently replace the texture by a lighter one.

**Comment by Seneral** [comment]
No problem, didn't test yet but looks great:)

**Comment by groud** [comment]
I tested with a smaller texture but faced a little bug. It is now fixed. 
I pushed the smaller texture and also changed the texture import properties (just in case).

**Comment by Seneral** [comment]
Sorry for the late reply, kinda forgot that I wanted to test it:/
It has a little coordinate bug indeed, the texture should line up with the actual canvas space. For that to happen it needs to have it's origin at the center, and the scale has to be right (I think exactly 100px or something like that). You can test this by enabling snapping (hold strg while dragging a node) and it should snap to the grid:)

**Comment by groud** [comment]
Should be ok now. :)

**Comment by Seneral** [comment]
Yup, thank you! :)

**Pull request merged**
