### PR TITLE
Feature to change the background color of a Node

### PR DESCRIPTION
**Pull request by GilFerraz**
Feature to change the background color of a Node via the SetBackgroundColor(Color color) method.
This is useful to better differentiate between node types in complex systems.

### CODE REVIEW

**Comment by Seneral** [comment]
Thankd Gil, good idea!
Theres a function called RTEditorGUI.ColorToTex which creates a texture with a color. Maybe use that, instead of creating a new namespace, even if its a extension:) Although I like your implementation better...
Second note, please cache the GUIStyle and create the texture only when needed, in SetBackgroundTexture. Creating that multiple times a Frame would leak alot of memory;)

**Comment by Seneral** [comment]
So, fixed most of that myself.
Are you ok with this?

- Cached GUIStyle and Texture
- Changed to tint normal box texture instead of a solid color for better look
- Changed drawing behaviour of header -> body and header will be colored
- Allowed to set background color outside of GUI functions (like Node.Create)

**Comment by Seneral** [comment]
screenshot3

**Comment by GilFerraz** [comment]
Hi! :)
I'm glad you liked my suggestion. I am working on a custom Dailogue System for a project. I realized that I had way to many different Node types available and things were getting pretty chaotic on the editor side, so that's when I came up with the coloring idea.
Sorry for not responding or edition the code with your suggestions sooner, but I have been very busy lately :/
I'm glad you were able to make the necessary corrections. The final feature looks pretty cool and well implemented :)

**Comment by Seneral** [comment]
No problem, and indeed, bigger canvases can get very messy:D I think this will help alot, thanks!
If you've got any nice screens to share, don't hesitate to post them on the forums;)

**Pull request merged**
