### PR TITLE
Virtual method for drawing to the sceneview from the selected node

### PR DESCRIPTION
**Pull request by Barsonax**
NodeEditor_Barsonax: Added a new virtual method named OnSceneGUI to Node.cs to provide a possibility to draw stuff to the scene view. This gets called from the NodeEditorWindow.cs when the onSceneGUIDelegate of the SceneView gets called.

### CODE REVIEW

**Comment by Seneral** [comment]
Thanks again:) For the record, we had a conversation about this before.

So is there any way you can revert the redundant tabs/spaces that github shows as changes? Maybe toggling off any auto-format tools like reshaper, they seem to have replaced tabs in the files you're editing with spaces...
IMO tabs are way easier to work with than single spaces. So I appreciate it if you can revert this:)

**Comment by Barsonax** [comment]
Iam currently at work but ill try to convert back to spaces once iam back

**Comment by Barsonax** [comment]
I made a new pull request with tabs instead of spaces

**Comment by Seneral** [comment]
Ok I'll close this one then I guess:)

**Pull request closed without merging**
