### PR TITLE
Use foreach instead of for, for code readability.

### PR DESCRIPTION
**Pull request by groud**
This greatly improves the code readability, at it does not need a "counter" variable.

### CODE REVIEW

**Comment by pmhpereira** [comment]
Probably because of the [better performance](http://stackoverflow.com/questions/365615/in-net-which-loop-runs-faster-for-or-foreach/365658#365658).

Shouldn't be a issue, because all the Lists are pretty small.

**Comment by Seneral** [comment]
Huh, I somewhere read that when you reference the iterated variable more than twice in the loop, you should use foreach, else it's faster to use for... Which is correct now?

**Comment by Seneral** [comment]
http://www.dotnetperls.com/for-foreach
Maybe you can adjust this to when a variable was only acessed once, leave it as for, and when it's acessed multiple times (or sometimes even the cached value), change it to forach? That's best for performace. But as pmhpereira said, doesn't really matter anyway.
I'm simply used to use for loops instead of foreach most of the time;)

**Comment by groud** [comment]
In fact the performance issue truely depends on the structure you are iterating on. But however, at this scale we are not talking at all about performance.

I think that the code would greatly benefit from such modification, not because it would perform better, but because that is FAR more readable. I think at this point it is more important than performance. :)

**Comment by Seneral** [comment]
^^ Can you fix these three occurances to a for loop again? I think that is the only way:/

**Comment by groud** [comment]
I'll have a look this evening. :)

By the way, concerning about the performance, according to [this](http://stackoverflow.com/questions/11179156/how-is-foreach-implemented-in-c) and [this](http://stackoverflow.com/questions/21531131/does-the-c-sharp-compiler-optimize-foreach-blocks-when-its-contents-have-the-con),
when a foreach loop is applied to an array, it is compilated into normal indexing loop (well a good compilator should...) .
Unless they are wrong, both solutions must be equivalent in term of performance. :)

**Comment by Baste-RainGames** [comment]
Unity's old mono compiler has a bug where foreach loops generates (40 bytes of) garbage on anything that's not a normal array (usually a List, like in the conditions list here).

This has caused a huge amount of confusion on the forums about what's good practice and what's not.  Generally, I'd say that that this is not an issue, and the readability wins out. This is a plugin though, and it's nice to be able to use plugins like a black box without having to worry about their memory usage.

Up to you guys, I just figured I'd chip in the facts.

**Comment by Seneral** [comment]
Thanks for the clarification:) I'd be ok with the for loops besides the above mentioned three exceptions where a for loop is needed. Then I would merge if everyone is oke with that.

**Comment by groud** [comment]
Done. :)

**Comment by Seneral** [comment]
Anyway, can be added at a later date;)

**Comment by Seneral** [comment]
Seems like one of the commits throws an error where you replaced the for with a foreach loop, but the cnt is still referenced in the loop. Reverting back to for loop, this is necessary.

**Pull request merged**
