### PR TITLE
Added Keyboard Support for moving nodes

### PR DESCRIPTION
**Pull request by ReevMich**
using the arrow keys
As well as if you hold shift it increases the movement amount for the node.

This is { TheCaptainJuneBug } from the Node Editor Unity forum.

### CODE REVIEW

**Comment by Seneral** [comment]
Cool, seems neat. Any use case you specifically designed it for or is it just 'nice -to-have'? ;)

Anyway, is there a reason to use reflection to get the handled hotkey when it's hardcoded? That seems like a 'waste' of resources there...
Also, but this is not too important, you could just stack all HotKeyAttributes on the single main method and then check for the key (inputInfo.inputEvent.keyCode). It would minimise code and is (atleast compared to the reflection method) more optimized. :)

**Comment by Seneral** [comment]
Also, the enum MoveNodeDirection seems to be redundant:)

**Comment by ReevMich** [comment]
Ahh, gotcha, yeah very new to a lot of this. 

It was a feature i use a lot. 

Those are some adjustments i will definitely make. Thank you for the information :)

**Comment by Seneral** [comment]
Cool, no problem:) That's what pull requests are for:)

**Comment by Seneral** [comment]
Really clean now, I'll merge now. Thanks!

**Comment by ReevMich** [comment]
yaay! :) my first actual contribution. I will continue to contributing this awesome project :)

**Comment by Seneral** [comment]
Cool, always nice to see other people contributing! Don't hesitate if you find something you would want to change/add;)

**Pull request merged**
