### PR TITLE
Master

### PR DESCRIPTION
**Pull request by TwoOfDiamonds**
1. I added the possibility to return null from the Node.Create function in order to support things like: the user wants an unique node and checks that on create so if there is a similar node already in existance the function will return null
2. I added a simple IntField

### CODE REVIEW

**Comment by Seneral** [comment]
There's already an IntField in RTEditorGUI, isn't it? I think it's just a wrapper for FloatField, casting to int, but it works...
Allowing unique nodes is nice though, thank you!
Also, I changed the target branch to develop to keep it tidy;)

**Comment by TwoOfDiamonds** [comment]
Just thought it will be nice to have it there explicitly :smile:

**Comment by TwoOfDiamonds** [comment]
Also, I got another commit to fix the case when the Create function returns null since that will mess up the node type registration in NodeTypes.cs . After this is merged I will create a pull request for that one too, ok?

**Comment by Seneral** [comment]
Better to add that commit to this pull request so it is together;)

**Comment by TwoOfDiamonds** [comment]
Note: the 3rd commit was messed up

**Comment by Seneral** [comment]
Can you remove both commit 3&4? I've previously committed a fix that removes the modified line in NodeTypes.cs that calls node.Create because it was not needed. Seems this is causing the merge conflicts;)
Also, two is redundant, as said previously...
So the fix you mentioned would also be not needed, I did not immediately realized this but as I said above the line we're talking about has been removed;)

**Comment by Seneral** [comment]
Or rather, can you create a new pull request with only your first commit in it? Maybe pull the develop branch in your develop to get it updated and then apply your first commit and it if works, create a new PR?
Hope you can follow me why;)

**Pull request closed without merging**
